### ISSUE TITLE
Get dataset metadata

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#1]
I see two ways of getting a list of all datasets + their metadata:
1. Through the Movebank Data Repository (which uses the Dryad repo software)
2. Through DataCite

I've currently implemented method 2: https://github.com/peterdesmet/movebank2gbif/blob/master/notebooks/get-movebank-data.ipynb. It has the advantage that this code can be reused to query any dataset on DataCite (which is a much larger metadata registry than Dryad, Movebank or GBIF, as it contains all three of these). Oddly though, you need to be authenticated to get metadata from a single dataset. It seems though, that you can get all the metadata you need through the search interface.

I've currently dumped all datasets + metadata I could find in https://github.com/peterdesmet/movebank2gbif/blob/master/data/datasets.csv

@sarahcd, can you verify:
- That this file contains all the necessary metadata
- That this file contains all the public datasets. I already noticed that it not only contains the main dataset, but all files as records too.

**Comment by sarahcd** [comment]
I agree getting dataset through DataCite seems best since this method can be widely used, and for now can't think of any advantage to accessing through the repository. The DataCite metadata are also I think in a clearer format, following DataCite's schema, than what you obtain through the repository (which combines Dublin Core and DataCite elements), and should by necessity be kept in compliance with their schema in the future.

I believe this should include all the metadata we need. We may need to parse the relatedIdentifier field because it contains information about related papers (IsSupplementTo), relationships between files within a data package (IsPartOf/HasPart, see below), and will indicate cases where one data package has been superceded by another (IsPreviousVersionOf/IsNewVersionOf).

All datasets published in Movebank have the CC0 (public) license. They all consist of a "data package" including a DOI for the package (linked to a landing page URL) and one for each file that are the same base DOI with an extension /1, /2.../n (and each of these also has its own landing page URL). This is exactly modeled based on Dryad.

**Comment by peterdesmet** [comment]
Decided to indeed retrieve all metadata via DataCite.

Advantages:
1. It has the same metadata as in the data repository
2. An effort has been made to make sure that metadata is correct
3. It's in a more common format (used for any package registered via DataCite)
4. We can get the metadata when getting a list of files

Disadvantages:
1. We will need to parse out some fields, such as `relatedIdentifiers` and `subject` (to get species info).
2. We will need to use the data repository service anyway to get the file URLs (see #3)

**Comment by peterdesmet** [comment]
Getting metadata from DataCite is now implemented in R as part of https://inbo.github.io/movepub/reference/write_dwc.html (repo https://github.com/inbo/movepub).
