### ISSUE TITLE
Some Movebank datasets have no metadata on DataCite

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#2]
I found 10 Movebank datasets on DataCite, that have no metadata on DataCite. See https://github.com/peterdesmet/movebank2gbif/blob/master/data/datasets.csv#L212

@sarahcd I assume this should not have happened? Is there a way to fix this?

**Comment by sarahcd** [comment]
Thanks for pointing this out @peterdesmet. I had no record of these as being related to any submissions, so checked with my colleagues at the Uni Konstanz Library, and the best we can tell is that these DOIs were mistakenly issued when a former employee working on the project was doing some testing shortly after we started the repository. We have a test prefix with DataCite that should have been used, and which we have used/will use for future testing. 

At this point, since these DOIs are not referenced anywhere, and since we can't delete existing DOIs, we plan to just leave them as is. My recommendation would be to filter the search for contributor: "Movebank Data Repository" (as you describe at https://github.com/peterdesmet/movebank2gbif/blob/master/scripts/get-movebank-data.ipynb). The repository is now set up to include this automatically with all DOIs, so this will get us all current and future relevant DOIs. The first 3 DOIs we issued do not have this—although I could and should probably update the metadata to include it—but they are superceded by newer DOIs so can safely be ignored. More on this in my response to https://github.com/peterdesmet/movebank2gbif/issues/1.

**Comment by peterdesmet** [comment]
> The first 3 DOIs we issued do not have this

If I understand correctly, those will have `IsPreviousVersionOf` in `relatedIdentifiers` and thus be filtered out (#1)?

Too bad DOIs can be deleted if they're really incorrect or just for testing purposes. 😄

**Comment by sarahcd** [comment]
Yes and yes.
1. We can get the metadata as 1 record for each current (not superceded) dataset ("data package") by filtering to
2. exclude DOIs ending in "/#": the number extension is for each file within a dataset (the MDR and Dryad issue a DOI for each file in a dataset, but in GBIF there will be only 1 DOI for the dataset)
3. exclude DOIs with a relatedIdentifier = IsPreviousVersionOf
4. exclude DOIs with contributor != "Movebank Data Repository"
5. This brings up another widely applicable issue that we don't need to resolve now but we should think about: Some small percentage of datasets have been/will be superceded by a newer dataset. This could happen if e.g. an error is found in a published data file and is corrected in a new version or a more complete version of a dataset, including all of a published dataset, is later published. As far as I know, DataCite doesn't have any way to distinguish between these. The best way I have found to deal with this is using relatedIdentifier as described, but it's not perfect. A fully automated system would need to look for this and update/replace old versions as needed.

On deleting DOIS: From DataCite's perspective (as I understand), their goal in issuing DOIs is to maintain a permanent link to a file that can be referenced, cited, resolved, and downloaded and stored elsewhere. So allowing deletion defeats the purpose, sort of the same way that a published research article can't be "deleted" even if the study turns out later to be bogus! I do wish there was a better way to flag a dataset as superceded (and maybe offer a flag for "invalid"?) and for them to offer an automated way of notifying people when they go to resolve a DOI that has been superceded and offering to redirect them to the current version.

**Comment by peterdesmet** [comment]
Ok, the filters are also described in #6. I'll close this issue.
