### ISSUE TITLE
Find example datasets for DwC mapping

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#4]
To map the Movebank data model to Darwin Core, we'll need an example file which contains (ideally) all possible fields from the Movebank data model. @sarahcd, do you know such an exemplar dataset?

**Comment by sarahcd** [comment]
@peterdesmet so you mean all possible attributes, ie as listed at https://www.movebank.org/node/2381? There won't be one dataset with all fields, just because different fields are important/irrelevant to different types of datasets. I could 
- find one that includes as many of the most-used fields as possible,
- create (but couldn't publish) a dummy file that includes all the fields we currently have in the database
- pull us a csv of fields in the database that we could use to map fields to DC. 
  Which of these would be useful?

**Comment by peterdesmet** [comment]
Option 1 would be useful.

**Comment by sarahcd** [comment]
I'm going to give this a try with http://dx.doi.org/10.5441/001/1.sj8t3r11 which includes most of the most commonly-used attributes, and not many uncommonly used ones.

**Comment by peterdesmet** [comment]
Will be tackled as part of https://github.com/inbo/movepub.
