### ISSUE TITLE
Parse metadata

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#7]
If the data is provided as Dublin Core (DC), GBIF can parse those:
- In the registry ([code](https://github.com/gbif/registry/blob/master/registry-metadata/src/main/java/org/gbif/registry/metadata/parse/DublinCoreRuleSet.java)) when harvesting a dataset with DC metadata: DC => registry dataset object
- In the IPT ([code](https://github.com/gbif/gbif-metadata-profile/blob/master/src/main/java/org/gbif/metadata/handler/DcHandler.java)) on resource creation, when importing a dataset with DC metadata: DC => EML

So, if we have the Movebank metadata in DC, it **doesn't make a lot of sense to map those ourselves to EML**. The only advantage we loose is that in EML we would be able to express more detailed info, but if the source metadata is in DC, any added info would be derived anyway.

GBIF folks couldn't immediately find a production DwC-A with DC metadata, but there is [one as a test file for the dwca-io](https://github.com/gbif/dwca-io/blob/dwca-reader-1.16/src/test/resources/metadata/worms_dc.xml). See the code mentions above to see which items get parsed.

**Comment by peterdesmet** [comment]
An alternative to Dublin Core is to provide the metadata in the DataCite format (which has apparently changed to version 4.0, see https://github.com/gbif/ipt/issues/1280).

@kbraak, can GBIF parse metadata provided in that format?

**Comment by kbraak** [comment]
No sorry, GBIF cannot parse metadata provided in DataCite format. 

Just a quick reminder to please include a GBIF-supported license in the EML or DC metadata document: either CC-BY 4.0, CC-BY-NC 4.0 or CC0 1.0.

Instructions on how to apply a license to a dataset using the IPT can be found [here](https://github.com/gbif/ipt/wiki/IPT2ApplyingLicense.wiki) in case the IPT is used to produce the metadata document.

Otherwise if you produce an EML document by hand, please note that you can insert a machine readable license inside the intellectualRights block. E.g. for CC-BY 4.0:

```
  <intellectualRights>
    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC-BY) 4.0 License</citetitle></ulink>.</para>
  </intellectualRights>

```

**Comment by peterdesmet** [comment]
Metadata is now converted to EML as part of `write_dwc()` in https://github.com/inbo/movepub.
